### ISSUE TITLE
Support HK region

### ISSUE THREAD

**Issue by xinlaoda** [awslabs/amazon-s3-data-replication-hub-plugin#18]
**Is your feature request related to a problem? Please describe.**
If the customer want to copy S3 objects to China region, then deploying this hub in HK region could be best selection.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by daixba** [comment]
Hi @xinlaoda , This solution can be deployed in ap-east-1 region.  If the customer want to copy S3 objects to China region, they can also deploy this solution in China regions if needed.  Please follow the guide in readme of this repo.

If you have more issues deploying that in HK region, please share more details, then I will check.
