### ISSUE TITLE
费用问题

### ISSUE THREAD

**Issue by yjghddp** [awslabs/amazon-s3-data-replication-hub-plugin#24]
空跑了2个星期，产生了950RMB费用。其中有18,803,179.000 个S3 PUT, COPY, POST, or LIST requests
为什么会有这么多请求，我都是在空跑的，没有传输任何S3对象

**Comment by JoeShi** [comment]
您好，可以看一下 过去两周 CloudWatch 的截图么？创建任务后，可以在CloudWatch 看到任务

**Comment by yjghddp** [comment]
不好意思，是我的问题。需求是两边相互同步，导致部署了两次这套方案，即：
第一次部署：A bucket ==> B bucket
第二次部署：B bucket==> A bucket
从而死循环了。我已通过增加C==>D来解决这个问题。

另外想请教一下，如果部署在第三方账号C上，令A bucket ==> B bucket，那么C账号必须有A和B的创建SQS、CW等权限，这些权限怎么给到C呢？通过模板中aksk参数？

**Comment by daixba** [comment]
如果同步的是A，B 账号， 但是solution 部署在C 账号， 只会在C账号会生成 SQS，CW 等resource， 并且相关权限都配置好了，不需要你做任何操作。  A，B账号不会创建任何resource， 但是你需要提供对A，B账号相关的桶 有读或写的权限 （通过提供AK SK，并维护在System Manager里）

**Comment by daixba** [comment]
Close this issue.
