### ISSUE TITLE
Does this Solution work for S3 from us standard account to US GovCloud?

### ISSUE THREAD

**Issue by jaydkar** [awslabs/amazon-s3-data-replication-hub-plugin#97]
Hi,

Will this Solution work to move S3 objects from US Standard region (us-east-1) to US Gov Region?

I am trying to deploy the S3 data replication plugin for this use case. 
Since this plugin is not available in US Gov (I tried, and then read the docs) , I have this deployed in us east 1. Source bucket is in us-east-1 and I am trying to move to a bucket in my govcloud account... 

Do I need to provide access keys for the gov cloud region?

I keep getting:
Error listing objects in destination bucket - operation error S3: ListObjectsV2, https response error StatusCode
api error InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

**Comment by YikaiHu** [comment]
Hi @jaydkar, sorry for late reply.

Yes, it support transfer between Standard region and US Gov Region.

For your case, you should create a secret key in Secret Manager in us-east-1, which value is your GovCloud Account's AKSK. (Please follow the format: https://github.com/awslabs/amazon-s3-data-replication-hub-plugin/blob/main/docs/DEPLOYMENT_EN.md#3-configure-credentials)
